package com.snoworca.IdxDB.collections;


import com.snoworca.cson.CSONObject;

import java.util.ArrayList;
import java.util.Collection;
import java.util.concurrent.atomic.AtomicBoolean;

public class IDxCollectionImpl extends IDxTransactionAbstractCollection implements IDxCollection, Restorable{

    private ArrayList<StoredInfo> dataPositions = new ArrayList<>();
    private AtomicBoolean isInitializationCompleted = new AtomicBoolean(false);



    private String idKey;
    private final boolean isIdKeyAutoGenerated;



    IDxCollectionImpl(CollectionOption collectionOption) {
        this.idKey = collectionOption.getIdKey();
        this.isIdKeyAutoGenerated = idKey == null;
        if(this.idKey == null) {
            this.idKey = "__id";
        }
    }


    @Override
    public CommitResult commit() {
        CommitResult result = new CommitResult();

        return result;
    }

    @Override
    public Collection<CSONObject> find(CSONObject query) {
        return null;
    }

    @Override
    public void findAll() {

    }

    @Override
    public void restore(StoredInfo storedInfo) {
        dataPositions.add(storedInfo);
    }

    @Override
    public void end() {
        // 인덱스 넣어야함.

        isInitializationCompleted.set(true);
    }
}
